[project]
name = "arc-prize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "kaggle>=1.7.4.5",
    "pandas>=2.3.2",
    "torch>=2.8.0",
]
